Name: transform.rpc
DevServer:
  Enabled: true
Log:
  Mode: console
ListenOn: 10.8.0.22:8081
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: transform.rpc
DataSource: root:123456@tcp(localhost:3306)/gozero
Table: shorturl
Cache:
  - Host: localhost:6379
