// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	user "user/api/internal/handler/user"
	"user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 根据id 获取用户
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.GetUserByIdHandler(serverCtx),
			},
			{
				// 创建用户
				Method:  http.MethodPost,
				Path:    "/user/create",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				// 删除用户
				Method:  http.MethodPost,
				Path:    "/user/delete",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				// 根据所有用户
				Method:  http.MethodGet,
				Path:    "/user/getAllUser",
				Handler: user.GetAllUserHandler(serverCtx),
			},
			{
				// 更新用户
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpdateUserHandler(serverCtx),
			},
		},
	)
}
