// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateUserReq struct {
	Name  string `json:"name"`
	Phone string `json:"phone,omitempty"`
}

type CreateUserResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type DeleteUserReq struct {
	Id string `json:"id"`
}

type DeleteUserResp struct {
	Id int64 `json:"id"`
}

type GetListUserReq struct {
}

type GetListUserResp struct {
	Data []UserInfo `json:"userInfo"`
}

type GetUserReq struct {
	Id string `json:"id"`
}

type GetUserResp struct {
	Id int64 `json:"id"`
}

type UpdateUserReq struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone,omitempty"`
}

type UpdateUserResp struct {
	Id int64 `json:"id"`
}

type UserInfo struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone,omitempty"`
}
